<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Homework8</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-991b1886d3c685c7aa2b62b80640c7af.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="fullcontent quarto-light">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Homework8</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'janitor' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'janitor'

The following objects are masked from 'package:stats':

    chisq.test, fisher.test</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidymodels' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ────────────────────────────────────── tidymodels 1.4.1 ──
✔ broom        1.0.10     ✔ rsample      1.3.1 
✔ dials        1.4.2      ✔ tailor       0.1.0 
✔ infer        1.0.9      ✔ tune         2.0.1 
✔ modeldata    1.5.1      ✔ workflows    1.3.0 
✔ parsnip      1.3.3      ✔ workflowsets 1.1.1 
✔ recipes      1.3.1      ✔ yardstick    1.3.2 </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'broom' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dials' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'infer' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'modeldata' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'parsnip' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'recipes' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'rsample' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tailor' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tune' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'workflows' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'workflowsets' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'yardstick' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ dplyr::filter()   masks stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'glmnet' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix

Attaching package: 'Matrix'

The following objects are masked from 'package:tidyr':

    expand, pack, unpack

Loaded glmnet 4.1-10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart.plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'rpart.plot' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: rpart

Attaching package: 'rpart'

The following object is masked from 'package:dials':

    prune</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vip)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'vip'

The following object is masked from 'package:utils':

    vi</code></pre>
</div>
</div>
<section id="homework-8" class="level2">
<h2 class="anchored" data-anchor-id="homework-8">Homework 8</h2>
<section id="reading-in-data" class="level3">
<h3 class="anchored" data-anchor-id="reading-in-data">Reading in Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Fixing nchar error</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"SeoulBikeData.csv"</span>, <span class="at">locale =</span> <span class="fu">locale</span>(<span class="at">encoding =</span> <span class="st">"latin1"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 8760 Columns: 14
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (4): Date, Seasons, Holiday, Functioning Day
dbl (10): Rented Bike Count, Hour, Temperature(°C), Humidity(%), Wind speed ...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</section>
<section id="eda" class="level3">
<h3 class="anchored" data-anchor-id="eda">EDA</h3>
<section id="checking-for-missing-data" class="level4">
<h4 class="anchored" data-anchor-id="checking-for-missing-data">Checking for Missing Data</h4>
<p>To begin the Exploratory Data Analysis, I first checked for any missing columns. Missing values can potentially introduce bias (or errors) in any modeling done down the road.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     Date         Rented Bike Count                      Hour 
                        0                         0                         0 
          Temperature(°C)               Humidity(%)          Wind speed (m/s) 
                        0                         0                         0 
         Visibility (10m) Dew point temperature(°C)   Solar Radiation (MJ/m2) 
                        0                         0                         0 
             Rainfall(mm)             Snowfall (cm)                   Seasons 
                        0                         0                         0 
                  Holiday           Functioning Day 
                        0                         0 </code></pre>
</div>
</div>
<p>The results show that there is no missing data in the current data set, meaning the data set is complete.</p>
</section>
<section id="checking-columns-types-and-values-within-columns" class="level4">
<h4 class="anchored" data-anchor-id="checking-columns-types-and-values-within-columns">Checking Columns Types and Values within Columns</h4>
<p>The next step is to check if each variable is stored under the correct data type and that the values of each variable make sense given the variable definitions.Categorical variables need to have their unique values checked as well.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 8,760
Columns: 14
$ Date                        &lt;chr&gt; "01/12/2017", "01/12/2017", "01/12/2017", …
$ `Rented Bike Count`         &lt;dbl&gt; 254, 204, 173, 107, 78, 100, 181, 460, 930…
$ Hour                        &lt;dbl&gt; 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, …
$ `Temperature(°C)`           &lt;dbl&gt; -5.2, -5.5, -6.0, -6.2, -6.0, -6.4, -6.6, …
$ `Humidity(%)`               &lt;dbl&gt; 37, 38, 39, 40, 36, 37, 35, 38, 37, 27, 24…
$ `Wind speed (m/s)`          &lt;dbl&gt; 2.2, 0.8, 1.0, 0.9, 2.3, 1.5, 1.3, 0.9, 1.…
$ `Visibility (10m)`          &lt;dbl&gt; 2000, 2000, 2000, 2000, 2000, 2000, 2000, …
$ `Dew point temperature(°C)` &lt;dbl&gt; -17.6, -17.6, -17.7, -17.6, -18.6, -18.7, …
$ `Solar Radiation (MJ/m2)`   &lt;dbl&gt; 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, …
$ `Rainfall(mm)`              &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ `Snowfall (cm)`             &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ Seasons                     &lt;chr&gt; "Winter", "Winter", "Winter", "Winter", "W…
$ Holiday                     &lt;chr&gt; "No Holiday", "No Holiday", "No Holiday", …
$ `Functioning Day`           &lt;chr&gt; "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Date           Rented Bike Count      Hour       Temperature(°C) 
 Length:8760        Min.   :   0.0    Min.   : 0.00   Min.   :-17.80  
 Class :character   1st Qu.: 191.0    1st Qu.: 5.75   1st Qu.:  3.50  
 Mode  :character   Median : 504.5    Median :11.50   Median : 13.70  
                    Mean   : 704.6    Mean   :11.50   Mean   : 12.88  
                    3rd Qu.:1065.2    3rd Qu.:17.25   3rd Qu.: 22.50  
                    Max.   :3556.0    Max.   :23.00   Max.   : 39.40  
  Humidity(%)    Wind speed (m/s) Visibility (10m) Dew point temperature(°C)
 Min.   : 0.00   Min.   :0.000    Min.   :  27     Min.   :-30.600          
 1st Qu.:42.00   1st Qu.:0.900    1st Qu.: 940     1st Qu.: -4.700          
 Median :57.00   Median :1.500    Median :1698     Median :  5.100          
 Mean   :58.23   Mean   :1.725    Mean   :1437     Mean   :  4.074          
 3rd Qu.:74.00   3rd Qu.:2.300    3rd Qu.:2000     3rd Qu.: 14.800          
 Max.   :98.00   Max.   :7.400    Max.   :2000     Max.   : 27.200          
 Solar Radiation (MJ/m2)  Rainfall(mm)     Snowfall (cm)       Seasons         
 Min.   :0.0000          Min.   : 0.0000   Min.   :0.00000   Length:8760       
 1st Qu.:0.0000          1st Qu.: 0.0000   1st Qu.:0.00000   Class :character  
 Median :0.0100          Median : 0.0000   Median :0.00000   Mode  :character  
 Mean   :0.5691          Mean   : 0.1487   Mean   :0.07507                     
 3rd Qu.:0.9300          3rd Qu.: 0.0000   3rd Qu.:0.00000                     
 Max.   :3.5200          Max.   :35.0000   Max.   :8.80000                     
   Holiday          Functioning Day   
 Length:8760        Length:8760       
 Class :character   Class :character  
 Mode  :character   Mode  :character  
                                      
                                      
                                      </code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lapply</span>(data[<span class="fu">c</span>(<span class="st">"Seasons"</span>, <span class="st">"Holiday"</span>, <span class="st">"Functioning Day"</span>)], unique)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Seasons
[1] "Winter" "Spring" "Summer" "Autumn"

$Holiday
[1] "No Holiday" "Holiday"   

$`Functioning Day`
[1] "Yes" "No" </code></pre>
</div>
</div>
<p>The data set appears to be clean. Categorical variables have expected values; for example, <strong>Seasons</strong> has values such as “Winter”, <strong>Holiday</strong> has “No Holiday”, and <strong>Functioning Day</strong> has “Yes”. The numeric variables have expected ranges such as <strong>Hours</strong> not exceeding 24 and <strong>Humidity(%)</strong> not exceeding 100.</p>
</section>
<section id="converting-date-column" class="level4">
<h4 class="anchored" data-anchor-id="converting-date-column">Converting Date Column</h4>
<p>The date column is currently read simply as text so it needs to be converted to an actual Date object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>Date <span class="ot">&lt;-</span> <span class="fu">dmy</span>(data<span class="sc">$</span>Date)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This change will allow for time-based grouping and plotting later.</p>
</section>
<section id="convert-character-variables-to-factors" class="level4">
<h4 class="anchored" data-anchor-id="convert-character-variables-to-factors">Convert Character Variables to Factors</h4>
<p>Categorical variables are being changed from character to factor variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Seasons =</span> <span class="fu">as.factor</span>(Seasons),</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Holiday =</span> <span class="fu">as.factor</span>(Holiday),</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Functioning Day</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">as.factor</span>(<span class="st">`</span><span class="at">Functioning Day</span><span class="st">`</span>)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>They have been changed to factor variables for better summaries and modeling later on.</p>
</section>
<section id="rename-columns" class="level4">
<h4 class="anchored" data-anchor-id="rename-columns">Rename Columns</h4>
<p>The variables names are being converted to PascalCase making them easier to use.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span> <span class="fu">clean_names</span>(<span class="at">case =</span> <span class="st">"big_camel"</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 8,760
Columns: 14
$ Date                 &lt;date&gt; 2017-12-01, 2017-12-01, 2017-12-01, 2017-12-01, …
$ RentedBikeCount      &lt;dbl&gt; 254, 204, 173, 107, 78, 100, 181, 460, 930, 490, …
$ Hour                 &lt;dbl&gt; 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,…
$ TemperatureC         &lt;dbl&gt; -5.2, -5.5, -6.0, -6.2, -6.0, -6.4, -6.6, -7.4, -…
$ HumidityPercent      &lt;dbl&gt; 37, 38, 39, 40, 36, 37, 35, 38, 37, 27, 24, 21, 2…
$ WindSpeedMS          &lt;dbl&gt; 2.2, 0.8, 1.0, 0.9, 2.3, 1.5, 1.3, 0.9, 1.1, 0.5,…
$ Visibility10M        &lt;dbl&gt; 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2…
$ DewPointTemperatureC &lt;dbl&gt; -17.6, -17.6, -17.7, -17.6, -18.6, -18.7, -19.5, …
$ SolarRadiationMjM2   &lt;dbl&gt; 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0…
$ RainfallMm           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ SnowfallCm           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Seasons              &lt;fct&gt; Winter, Winter, Winter, Winter, Winter, Winter, W…
$ Holiday              &lt;fct&gt; No Holiday, No Holiday, No Holiday, No Holiday, N…
$ FunctioningDay       &lt;fct&gt; Yes, Yes, Yes, Yes, Yes, Yes, Yes, Yes, Yes, Yes,…</code></pre>
</div>
</div>
<p>Now variables like <strong>‘Rented Bike Count’</strong> appear as <strong>RentedBikeCount</strong> and <strong>‘Functioning Day’</strong> appear as <strong>FunctioningDay</strong>.</p>
</section>
<section id="create-summary-statistics" class="level4">
<h4 class="anchored" data-anchor-id="create-summary-statistics">Create Summary Statistics</h4>
<p>I explored RentedBikeCount across key categorical variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Five-Number Summary</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data<span class="sc">$</span>RentedBikeCount)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    0.0   191.0   504.5   704.6  1065.2  3556.0 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co">#RentedBikeCount Mean by Season</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>data <span class="sc">|&gt;</span> </span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Seasons) <span class="sc">|&gt;</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">MeanBikes =</span> <span class="fu">mean</span>(RentedBikeCount))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  Seasons MeanBikes
  &lt;fct&gt;       &lt;dbl&gt;
1 Autumn       820.
2 Spring       730.
3 Summer      1034.
4 Winter       226.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">#RentedBikeCount Mean by Holiday</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>data <span class="sc">|&gt;</span> </span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Holiday) <span class="sc">|&gt;</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">MeanBikes =</span> <span class="fu">mean</span>(RentedBikeCount))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  Holiday    MeanBikes
  &lt;fct&gt;          &lt;dbl&gt;
1 Holiday         500.
2 No Holiday      715.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">#RentedBikeCount Mean by Functioning Day</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>data <span class="sc">|&gt;</span> </span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(FunctioningDay) <span class="sc">|&gt;</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">MeanBikes =</span> <span class="fu">mean</span>(RentedBikeCount))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  FunctioningDay MeanBikes
  &lt;fct&gt;              &lt;dbl&gt;
1 No                    0 
2 Yes                 729.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Subsetting Data to Only Include Functioning Day = Yes</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span> <span class="fu">filter</span>(FunctioningDay <span class="sc">==</span> <span class="st">"Yes"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The mean rented bike count across FunctioningDay showed that when that variable takes on a value of “no”, the operation was in fact closed. Therefore, I subsetted the data to only include days in which the company was operational (FunctioningDay = “Yes”).</p>
</section>
<section id="summarize-the-data-to-have-only-one-observation-per-day" class="level4">
<h4 class="anchored" data-anchor-id="summarize-the-data-to-have-only-one-observation-per-day">Summarize the Data to have only One Observation per Day</h4>
<p>The current data set records values on an hourly basis, so the data is going to be summarized in a way that each observation represents the counts and averages for the <strong>day</strong>. This will allows us to work with the data on a day by day basis, not hour by hour basis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>DailyData <span class="ot">&lt;-</span> data <span class="sc">|&gt;</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Date, Seasons, Holiday) <span class="sc">|&gt;</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">TotalBikeCount =</span> <span class="fu">sum</span>(RentedBikeCount, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">TotalRainfallMm =</span> <span class="fu">sum</span>(RainfallMm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">TotalSnowfallCm =</span> <span class="fu">sum</span>(SnowfallCm, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">MeanTempC =</span> <span class="fu">mean</span>(TemperatureC, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">MeanHumidityPercent =</span> <span class="fu">mean</span>(HumidityPercent, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">MeanWindSpeedMs =</span> <span class="fu">mean</span>(WindSpeedMS, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">MeanVisibility10M =</span> <span class="fu">mean</span>(Visibility10M, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">MeanDewPointC =</span> <span class="fu">mean</span>(DewPointTemperatureC, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">MeanSolarMjm2 =</span> <span class="fu">mean</span>(SolarRadiationMjM2, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a><span class="co">#Saving the New Data </span></span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(DailyData, <span class="st">"SeoulBikeDataDaily.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The new data set that we are going to work with contains 353 daily observations (as opposed to 8465 before) representing the 353 days out the year that the rental shop was open. It now contains summarized daily weather information and total daily rentals.</p>
</section>
<section id="exploring-relationships-coorelations-using-new-data-set" class="level4">
<h4 class="anchored" data-anchor-id="exploring-relationships-coorelations-using-new-data-set">Exploring Relationships / Coorelations (using New Data Set)</h4>
<p>I am going to check the daily summaries using the new data set. I am also going to check the correlations between numeric variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Basic Summaries</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(DailyData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Date              Seasons         Holiday    TotalBikeCount 
 Min.   :2017-12-01   Autumn:81   Holiday   : 17   Min.   :  977  
 1st Qu.:2018-02-27   Spring:90   No Holiday:336   1st Qu.: 6967  
 Median :2018-05-28   Summer:92                    Median :18563  
 Mean   :2018-05-28   Winter:90                    Mean   :17485  
 3rd Qu.:2018-08-24                                3rd Qu.:26285  
 Max.   :2018-11-30                                Max.   :36149  
 TotalRainfallMm  TotalSnowfallCm    MeanTempC       MeanHumidityPercent
 Min.   : 0.000   Min.   : 0.000   Min.   :-14.738   Min.   :22.25      
 1st Qu.: 0.000   1st Qu.: 0.000   1st Qu.:  3.304   1st Qu.:47.58      
 Median : 0.000   Median : 0.000   Median : 13.738   Median :57.17      
 Mean   : 3.576   Mean   : 1.863   Mean   : 12.776   Mean   :58.17      
 3rd Qu.: 0.500   3rd Qu.: 0.000   3rd Qu.: 22.592   3rd Qu.:67.71      
 Max.   :95.500   Max.   :78.700   Max.   : 33.742   Max.   :95.88      
 MeanWindSpeedMs  MeanVisibility10M MeanDewPointC     MeanSolarMjm2    
 Min.   :0.6625   Min.   : 214.3    Min.   :-27.750   Min.   :0.02917  
 1st Qu.:1.3042   1st Qu.:1087.0    1st Qu.: -5.188   1st Qu.:0.28333  
 Median :1.6583   Median :1557.8    Median :  4.612   Median :0.56500  
 Mean   :1.7261   Mean   :1434.0    Mean   :  3.954   Mean   :0.56773  
 3rd Qu.:1.9542   3rd Qu.:1874.3    3rd Qu.: 14.921   3rd Qu.:0.82000  
 Max.   :4.0000   Max.   :2000.0    Max.   : 25.038   Max.   :1.21667  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Correlation (Numeric Variables)</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>NumericVars <span class="ot">&lt;-</span> <span class="fu">select</span>(DailyData, <span class="fu">where</span>(is.numeric))</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cor</span>(NumericVars, <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    TotalBikeCount TotalRainfallMm TotalSnowfallCm MeanTempC
TotalBikeCount                1.00           -0.24           -0.27      0.75
TotalRainfallMm              -0.24            1.00           -0.02      0.14
TotalSnowfallCm              -0.27           -0.02            1.00     -0.27
MeanTempC                     0.75            0.14           -0.27      1.00
MeanHumidityPercent           0.04            0.53            0.07      0.40
MeanWindSpeedMs              -0.19           -0.10            0.02     -0.26
MeanVisibility10M             0.17           -0.22           -0.10      0.00
MeanDewPointC                 0.65            0.26           -0.21      0.96
MeanSolarMjm2                 0.74           -0.32           -0.23      0.55
                    MeanHumidityPercent MeanWindSpeedMs MeanVisibility10M
TotalBikeCount                     0.04           -0.19              0.17
TotalRainfallMm                    0.53           -0.10             -0.22
TotalSnowfallCm                    0.07            0.02             -0.10
MeanTempC                          0.40           -0.26              0.00
MeanHumidityPercent                1.00           -0.23             -0.56
MeanWindSpeedMs                   -0.23            1.00              0.21
MeanVisibility10M                 -0.56            0.21              1.00
MeanDewPointC                      0.63           -0.29             -0.15
MeanSolarMjm2                     -0.27            0.10              0.27
                    MeanDewPointC MeanSolarMjm2
TotalBikeCount               0.65          0.74
TotalRainfallMm              0.26         -0.32
TotalSnowfallCm             -0.21         -0.23
MeanTempC                    0.96          0.55
MeanHumidityPercent          0.63         -0.27
MeanWindSpeedMs             -0.29          0.10
MeanVisibility10M           -0.15          0.27
MeanDewPointC                1.00          0.38
MeanSolarMjm2                0.38          1.00</code></pre>
</div>
</div>
<p>Now I am going to exploring relationships using plots. Specifically, <em>Humidity vs Bike Rental Total</em>, <em>Trend over Over Time</em>, <em>Holiday Rentals vs Non-Holiday Rentals</em>, &amp; <em>Temperature vs Rentals (Colored by Season)</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Humidity vs Bike Rental Total </span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(DailyData, <span class="fu">aes</span>(<span class="at">x =</span> MeanHumidityPercent, <span class="at">y =</span> TotalBikeCount)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"cyan"</span>) <span class="sc">+</span> </span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Daily Bike Rentals vs Humidity"</span>,</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Mean Daily Humidity(%)"</span>,</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Total Daily Bike Rentals"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BikeRentalData_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows that there is not a strong relationship between humidity and daily bike rentals. The correlation is 0.04 along with the scatterplot leads up to conclude that humidity alone is not a driving force of consumer bike rental behavior.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Trend of Bike Rentals over Time</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(DailyData, <span class="fu">aes</span>(<span class="at">x =</span> Date, <span class="at">y =</span> TotalBikeCount, <span class="at">color =</span> Seasons)) <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Trend of Bike Rentals over Time"</span>,</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Date"</span>,</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Total Daily Bike Rentals"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BikeRentalData_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In the figure above, the daily trend over time shows rentals are low in the wintertime and then steadily increases through the spring into the summer. There is a small decline in late summer/early fall with a brief rebound in September/October before tapering off as winter approaches. Although there are clear fluctuations present, the overall trend is low bike rentals over the cold periods of the year and peak bike rentals occuring in the warm periods of the year.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Holiday vs Non-Holiday Bike Rentals</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(DailyData, <span class="fu">aes</span>(<span class="at">x =</span> Holiday, <span class="at">y =</span> TotalBikeCount, <span class="at">fill =</span> Holiday)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="at">aplha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Holiday vs Non-Holiday Bike Rentals"</span>,</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Holiday Status"</span>,</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Total Daily Bike Rentals"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in geom_boxplot(aplha = 0.5): Ignoring unknown parameters: `aplha`</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BikeRentalData_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the boxplot above, we can see that there are noticeably less bike rentals on holidays than on days that are not considered holidays.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Temperature vs Rentals (Colored by Season)</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(DailyData, <span class="fu">aes</span>(<span class="at">x =</span> MeanTempC, <span class="at">y =</span> TotalBikeCount, <span class="at">color =</span> Seasons)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Temperature vs Bike Rentals (Colored by Season)"</span>,</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Mean Daily Temperature (Celsius)"</span>,</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Total Daily Bike Rentals"</span>,</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Season"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BikeRentalData_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The figure above displays a positive relationship between temperature and rentals. The higher the temperature, the more bike rentals there are. Summer has the most rentals but it appears as it gets extremely hot, the rentals decline. Overall, warmer months promote more people to rent bikes and colder months have lower demand for bike rentals.</p>
</section>
</section>
<section id="split-the-data" class="level3">
<h3 class="anchored" data-anchor-id="split-the-data">Split the Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co">#For reproducibility</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Split Data 75/25 (Stratified by Seasons)</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>DailyDataSplit <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(DailyData, <span class="at">prop =</span> <span class="fl">0.75</span>, <span class="at">strata =</span> Seasons)</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>TrainingData <span class="ot">&lt;-</span> <span class="fu">training</span>(DailyDataSplit)</span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>TestData <span class="ot">&lt;-</span> <span class="fu">testing</span>(DailyDataSplit)</span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Checking Overall Ratio</span></span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(TrainingData) <span class="sc">/</span> <span class="fu">nrow</span>(DailyData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7450425</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(TestData) <span class="sc">/</span> <span class="fu">nrow</span>(DailyData)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2549575</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co">#10-fold CV split</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>CvFolds <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(TrainingData, <span class="at">v =</span> <span class="dv">10</span>, <span class="at">strata =</span> Seasons)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Checking the split balance for Training Data and Testing Data</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(TrainingData<span class="sc">$</span>Seasons))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   Autumn    Spring    Summer    Winter 
0.2281369 0.2547529 0.2623574 0.2547529 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(TestData<span class="sc">$</span>Seasons))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   Autumn    Spring    Summer    Winter 
0.2333333 0.2555556 0.2555556 0.2555556 </code></pre>
</div>
</div>
</section>
<section id="fitting-mlr-models" class="level3">
<h3 class="anchored" data-anchor-id="fitting-mlr-models">Fitting MLR Models</h3>
<section id="recipe1-creating-weekdayweekend-variable-factor-normalizing-numeric-variables-creating-dummy-variables" class="level4">
<h4 class="anchored" data-anchor-id="recipe1-creating-weekdayweekend-variable-factor-normalizing-numeric-variables-creating-dummy-variables">Recipe1: Creating Weekday/Weekend variable (factor), Normalizing Numeric Variables, Creating Dummy Variables</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating Weekday/Weekend Factor Variable // Normalizing Numeric Variables // Creating Dummy Variables</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>Recipe1 <span class="ot">&lt;-</span> <span class="fu">recipe</span>(TotalBikeCount <span class="sc">~</span> ., <span class="at">data =</span> TrainingData) <span class="sc">|&gt;</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Extracting day of the week</span></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_date</span>(Date, <span class="at">features =</span> <span class="st">"dow"</span>, <span class="at">label =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Creating the weekday/weekend variable</span></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_mutate</span>(</span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">DayType =</span> <span class="fu">factor</span>(<span class="fu">if_else</span>(Date_dow <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Sat"</span>, <span class="st">"Sun"</span>), <span class="st">"Weekend"</span>, <span class="st">"Weekday"</span>))</span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Removing Date and intermediate variable</span></span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(Date, Date_dow) <span class="sc">|&gt;</span></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Removing columns that have no variation (these columns contribute nothing to the upcoming models)</span></span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_zv</span>(<span class="fu">all_predictors</span>()) <span class="sc">|&gt;</span></span>
<span id="cb72-13"><a href="#cb72-13" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Normalizing the predictors (mean = 0, standard deviation = 1)</span></span>
<span id="cb72-14"><a href="#cb72-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_normalize</span>(<span class="fu">all_numeric_predictors</span>()) <span class="sc">|&gt;</span></span>
<span id="cb72-15"><a href="#cb72-15" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Create dummy variables for Seasons, Holiday, and DayType</span></span>
<span id="cb72-16"><a href="#cb72-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(<span class="fu">all_of</span>(<span class="fu">c</span>(<span class="st">"Seasons"</span>, <span class="st">"Holiday"</span>, <span class="st">"DayType"</span>)))</span>
<span id="cb72-17"><a href="#cb72-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-18"><a href="#cb72-18" aria-hidden="true" tabindex="-1"></a><span class="co">#Prepping and Baking</span></span>
<span id="cb72-19"><a href="#cb72-19" aria-hidden="true" tabindex="-1"></a>Recipe1_Prep <span class="ot">&lt;-</span> <span class="fu">prep</span>(Recipe1)</span>
<span id="cb72-20"><a href="#cb72-20" aria-hidden="true" tabindex="-1"></a>TrainingProcessed <span class="ot">&lt;-</span> <span class="fu">bake</span>(Recipe1_Prep, <span class="at">new_data =</span> TrainingData)</span>
<span id="cb72-21"><a href="#cb72-21" aria-hidden="true" tabindex="-1"></a>TestingProcessed <span class="ot">&lt;-</span> <span class="fu">bake</span>(Recipe1_Prep, <span class="at">new_data =</span> TestData)</span>
<span id="cb72-22"><a href="#cb72-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-23"><a href="#cb72-23" aria-hidden="true" tabindex="-1"></a><span class="co">#Quick Visual Check of Variables (No Date column // Dummy variables created // Numeric variables standardized)</span></span>
<span id="cb72-24"><a href="#cb72-24" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(TrainingProcessed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 263
Columns: 14
$ TotalRainfallMm     &lt;dbl&gt; -0.2975348, 2.6568122, -0.2975348, -0.2975348, -0.…
$ TotalSnowfallCm     &lt;dbl&gt; -0.2111987, -0.2111987, -0.2111987, -0.2111987, -0…
$ MeanTempC           &lt;dbl&gt; 1.04209038, 0.92394352, 0.89405093, 0.94387190, 0.…
$ MeanHumidityPercent &lt;dbl&gt; -0.21609367, 1.63817491, 0.92713959, 0.26908337, 0…
$ MeanWindSpeedMs     &lt;dbl&gt; -0.32812413, -1.08977647, 0.81435437, 1.39637172, …
$ MeanVisibility10M   &lt;dbl&gt; 1.14765109, 0.16549288, 0.06661677, 1.06766424, 0.…
$ MeanDewPointC       &lt;dbl&gt; 0.84997156, 1.25315875, 1.02039088, 0.88993857, 1.…
$ MeanSolarMjm2       &lt;dbl&gt; 0.8274593, -1.3770748, 0.9962399, 1.1027015, -0.38…
$ TotalBikeCount      &lt;dbl&gt; 26881, 10802, 29529, 31114, 27838, 29813, 28354, 3…
$ Seasons_Spring      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ Seasons_Summer      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ Seasons_Winter      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ Holiday_No.Holiday  &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,…
$ DayType_Weekend     &lt;dbl&gt; 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(TestingProcessed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 90
Columns: 14
$ TotalRainfallMm     &lt;dbl&gt; -0.297534830, -0.288971505, -0.186211610, -0.29753…
$ TotalSnowfallCm     &lt;dbl&gt; -0.2111987, -0.2111987, 0.7497533, -0.2111987, -0.…
$ MeanTempC           &lt;dbl&gt; -1.3016303, -1.1180044, -1.0881119, -1.4187096, -1…
$ MeanHumidityPercent &lt;dbl&gt; -0.79607542, -0.35272399, 0.87137212, -1.07212443,…
$ MeanWindSpeedMs     &lt;dbl&gt; -0.27064094, 3.02745738, -1.72209161, 0.26826402, …
$ MeanVisibility10M   &lt;dbl&gt; 0.9003354, -0.1185147, -0.4714765, 0.9032608, 0.18…
$ MeanDewPointC       &lt;dbl&gt; -1.3344653, -1.0566147, -0.6930748, -1.4741900, -1…
$ MeanSolarMjm2       &lt;dbl&gt; -1.03821536, -0.93175376, -1.01614405, -0.91877064…
$ TotalBikeCount      &lt;dbl&gt; 9539, 8729, 6669, 8032, 4632, 3776, 2620, 5605, 64…
$ Seasons_Spring      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ Seasons_Summer      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ Seasons_Winter      &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
$ Holiday_No.Holiday  &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
$ DayType_Weekend     &lt;dbl&gt; 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,…</code></pre>
</div>
</div>
</section>
<section id="recipe2-same-as-recipe-1-interactions-between-seasons-holidays-seasons-and-temp-temp-rainfall." class="level4">
<h4 class="anchored" data-anchor-id="recipe2-same-as-recipe-1-interactions-between-seasons-holidays-seasons-and-temp-temp-rainfall.">Recipe2: Same as Recipe 1 + interactions between seasons &amp; holidays, seasons and temp, temp &amp; rainfall.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Same Manipulations as Recipe 1</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>Recipe2 <span class="ot">&lt;-</span> <span class="fu">recipe</span>(TotalBikeCount <span class="sc">~</span> ., <span class="at">data =</span> TrainingData) <span class="sc">|&gt;</span></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_date</span>(Date, <span class="at">features =</span> <span class="st">"dow"</span>, <span class="at">label =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_mutate</span>(</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">DayType =</span> <span class="fu">factor</span>(<span class="fu">if_else</span>(Date_dow <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Sat"</span>, <span class="st">"Sun"</span>), <span class="st">"Weekend"</span>, <span class="st">"Weekday"</span>))</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(Date, Date_dow) <span class="sc">|&gt;</span></span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_zv</span>(<span class="fu">all_predictors</span>()) <span class="sc">|&gt;</span></span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_normalize</span>(<span class="fu">all_numeric_predictors</span>()) <span class="sc">|&gt;</span></span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(<span class="fu">all_of</span>(<span class="fu">c</span>(<span class="st">"Seasons"</span>, <span class="st">"Holiday"</span>, <span class="st">"DayType"</span>))) <span class="sc">|&gt;</span></span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a><span class="co">#Creating desired interactions</span></span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Seasons &amp; Holidays</span></span>
<span id="cb76-15"><a href="#cb76-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_interact</span>(<span class="sc">~</span><span class="fu">matches</span>(<span class="st">"^Seasons_(Autumn|Spring|Summer|Winter)$"</span>)</span>
<span id="cb76-16"><a href="#cb76-16" aria-hidden="true" tabindex="-1"></a>                <span class="sc">:</span> <span class="fu">matches</span>(<span class="st">"^Holiday_(Holiday|No</span><span class="sc">\\</span><span class="st">.Holiday)$"</span>))  <span class="sc">|&gt;</span></span>
<span id="cb76-17"><a href="#cb76-17" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Seasons &amp; Temperature</span></span>
<span id="cb76-18"><a href="#cb76-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_interact</span>(<span class="sc">~</span><span class="fu">matches</span>(<span class="st">"^Seasons_(Autumn|Spring|Summer|Winter)$"</span>)<span class="sc">:</span>MeanTempC) <span class="sc">|&gt;</span></span>
<span id="cb76-19"><a href="#cb76-19" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Temperature &amp; Rainfall</span></span>
<span id="cb76-20"><a href="#cb76-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_interact</span>(<span class="sc">~</span>MeanTempC<span class="sc">:</span>TotalRainfallMm) <span class="sc">|&gt;</span></span>
<span id="cb76-21"><a href="#cb76-21" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Eliminating all unnecessary linear combinations</span></span>
<span id="cb76-22"><a href="#cb76-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_lincomb</span>(<span class="fu">all_numeric_predictors</span>())</span>
<span id="cb76-23"><a href="#cb76-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb76-24"><a href="#cb76-24" aria-hidden="true" tabindex="-1"></a><span class="co">#Prepping and Baking</span></span>
<span id="cb76-25"><a href="#cb76-25" aria-hidden="true" tabindex="-1"></a>Recipe2_Prep <span class="ot">&lt;-</span> <span class="fu">prep</span>(Recipe2)</span>
<span id="cb76-26"><a href="#cb76-26" aria-hidden="true" tabindex="-1"></a>TrainingProcessed2 <span class="ot">&lt;-</span> <span class="fu">bake</span>(Recipe2_Prep, <span class="at">new_data =</span> TrainingData)</span>
<span id="cb76-27"><a href="#cb76-27" aria-hidden="true" tabindex="-1"></a>TestingProcessed2 <span class="ot">&lt;-</span> <span class="fu">bake</span>(Recipe2_Prep, <span class="at">new_data =</span> TestData)</span>
<span id="cb76-28"><a href="#cb76-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-29"><a href="#cb76-29" aria-hidden="true" tabindex="-1"></a><span class="co">#Quick visual check of interaction columns</span></span>
<span id="cb76-30"><a href="#cb76-30" aria-hidden="true" tabindex="-1"></a>TrainingProcessed2 <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="fu">matches</span>(<span class="st">"_x_"</span>)) <span class="sc">|&gt;</span> <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 263
Columns: 7
$ Seasons_Spring_x_Holiday_No.Holiday &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Seasons_Summer_x_Holiday_No.Holiday &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Seasons_Winter_x_Holiday_No.Holiday &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Seasons_Spring_x_MeanTempC          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Seasons_Summer_x_MeanTempC          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Seasons_Winter_x_MeanTempC          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ MeanTempC_x_TotalRainfallMm         &lt;dbl&gt; -0.3100581848, 2.4547443682, -0.26…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>TestingProcessed2 <span class="sc">|&gt;</span> <span class="fu">select</span>(<span class="fu">matches</span>(<span class="st">"_x_"</span>)) <span class="sc">|&gt;</span> <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 90
Columns: 7
$ Seasons_Spring_x_Holiday_No.Holiday &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Seasons_Summer_x_Holiday_No.Holiday &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Seasons_Winter_x_Holiday_No.Holiday &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ Seasons_Spring_x_MeanTempC          &lt;dbl&gt; 0.0000000, 0.0000000, 0.0000000, 0…
$ Seasons_Summer_x_MeanTempC          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Seasons_Winter_x_MeanTempC          &lt;dbl&gt; -1.3016303, -1.1180044, -1.0881119…
$ MeanTempC_x_TotalRainfallMm         &lt;dbl&gt; 0.387280348, 0.323071426, 0.202619…</code></pre>
</div>
</div>
</section>
<section id="recipe3-same-as-recipe-2-adding-in-quadratic-terms-for-each-numeric-predictor" class="level4">
<h4 class="anchored" data-anchor-id="recipe3-same-as-recipe-2-adding-in-quadratic-terms-for-each-numeric-predictor">Recipe3: Same as Recipe 2 + adding in quadratic terms for each numeric predictor</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Same as Recipe 2</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>Recipe3 <span class="ot">&lt;-</span> <span class="fu">recipe</span>(TotalBikeCount <span class="sc">~</span> ., <span class="at">data =</span> TrainingData) <span class="sc">|&gt;</span></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_date</span>(Date, <span class="at">features =</span> <span class="st">"dow"</span>, <span class="at">label =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_mutate</span>(</span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">DayType =</span> <span class="fu">factor</span>(<span class="fu">if_else</span>(Date_dow <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Sat"</span>, <span class="st">"Sun"</span>), <span class="st">"Weekend"</span>, <span class="st">"Weekday"</span>))</span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_rm</span>(Date, Date_dow) <span class="sc">|&gt;</span></span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_zv</span>(<span class="fu">all_predictors</span>()) <span class="sc">|&gt;</span></span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_normalize</span>(<span class="fu">all_numeric_predictors</span>()) <span class="sc">|&gt;</span></span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(<span class="fu">all_of</span>(<span class="fu">c</span>(<span class="st">"Seasons"</span>, <span class="st">"Holiday"</span>, <span class="st">"DayType"</span>))) <span class="sc">|&gt;</span></span>
<span id="cb80-11"><a href="#cb80-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_interact</span>(<span class="sc">~</span><span class="fu">matches</span>(<span class="st">"^Seasons_(Autumn|Spring|Summer|Winter)$"</span>)</span>
<span id="cb80-12"><a href="#cb80-12" aria-hidden="true" tabindex="-1"></a>                <span class="sc">:</span> <span class="fu">matches</span>(<span class="st">"^Holiday_(Holiday|No</span><span class="sc">\\</span><span class="st">.Holiday)$"</span>))  <span class="sc">|&gt;</span></span>
<span id="cb80-13"><a href="#cb80-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_interact</span>(<span class="sc">~</span><span class="fu">matches</span>(<span class="st">"^Seasons_(Autumn|Spring|Summer|Winter)$"</span>)<span class="sc">:</span>MeanTempC) <span class="sc">|&gt;</span></span>
<span id="cb80-14"><a href="#cb80-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_interact</span>(<span class="sc">~</span>MeanTempC<span class="sc">:</span>TotalRainfallMm) <span class="sc">|&gt;</span></span>
<span id="cb80-15"><a href="#cb80-15" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Quadratic Terms for each numeric predictor</span></span>
<span id="cb80-16"><a href="#cb80-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_poly</span>(</span>
<span id="cb80-17"><a href="#cb80-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">all_of</span>(<span class="fu">c</span>(</span>
<span id="cb80-18"><a href="#cb80-18" aria-hidden="true" tabindex="-1"></a>      <span class="st">"TotalRainfallMm"</span>,<span class="st">"TotalSnowfallCm"</span>,<span class="st">"MeanTempC"</span>,<span class="st">"MeanHumidityPercent"</span>,</span>
<span id="cb80-19"><a href="#cb80-19" aria-hidden="true" tabindex="-1"></a>      <span class="st">"MeanWindSpeedMs"</span>,<span class="st">"MeanVisibility10M"</span>,<span class="st">"MeanDewPointC"</span>,<span class="st">"MeanSolarMjm2"</span></span>
<span id="cb80-20"><a href="#cb80-20" aria-hidden="true" tabindex="-1"></a>    )),</span>
<span id="cb80-21"><a href="#cb80-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">degree =</span> <span class="dv">2</span>,</span>
<span id="cb80-22"><a href="#cb80-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">options =</span> <span class="fu">list</span>(<span class="at">raw =</span> <span class="cn">TRUE</span>),</span>
<span id="cb80-23"><a href="#cb80-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">keep_original_cols =</span> <span class="cn">TRUE</span></span>
<span id="cb80-24"><a href="#cb80-24" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb80-25"><a href="#cb80-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_lincomb</span>(<span class="fu">all_numeric_predictors</span>())</span>
<span id="cb80-26"><a href="#cb80-26" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb80-27"><a href="#cb80-27" aria-hidden="true" tabindex="-1"></a><span class="co">#Prepping and Baking</span></span>
<span id="cb80-28"><a href="#cb80-28" aria-hidden="true" tabindex="-1"></a>Recipe3_Prep <span class="ot">&lt;-</span> <span class="fu">prep</span>(Recipe3)</span>
<span id="cb80-29"><a href="#cb80-29" aria-hidden="true" tabindex="-1"></a>TrainingProcessed3 <span class="ot">&lt;-</span> <span class="fu">bake</span>(Recipe3_Prep, <span class="at">new_data =</span> TrainingData)</span>
<span id="cb80-30"><a href="#cb80-30" aria-hidden="true" tabindex="-1"></a>TestingProcessed3 <span class="ot">&lt;-</span> <span class="fu">bake</span>(Recipe3_Prep, <span class="at">new_data =</span> TestData)</span>
<span id="cb80-31"><a href="#cb80-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-32"><a href="#cb80-32" aria-hidden="true" tabindex="-1"></a><span class="co">#Quick visual check for quadratic terms</span></span>
<span id="cb80-33"><a href="#cb80-33" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(TrainingProcessed3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 263
Columns: 29
$ TotalRainfallMm                     &lt;dbl&gt; -0.2975348, 2.6568122, -0.2975348,…
$ TotalSnowfallCm                     &lt;dbl&gt; -0.2111987, -0.2111987, -0.2111987…
$ MeanTempC                           &lt;dbl&gt; 1.04209038, 0.92394352, 0.89405093…
$ MeanHumidityPercent                 &lt;dbl&gt; -0.21609367, 1.63817491, 0.9271395…
$ MeanWindSpeedMs                     &lt;dbl&gt; -0.32812413, -1.08977647, 0.814354…
$ MeanVisibility10M                   &lt;dbl&gt; 1.14765109, 0.16549288, 0.06661677…
$ MeanDewPointC                       &lt;dbl&gt; 0.84997156, 1.25315875, 1.02039088…
$ MeanSolarMjm2                       &lt;dbl&gt; 0.8274593, -1.3770748, 0.9962399, …
$ TotalBikeCount                      &lt;dbl&gt; 26881, 10802, 29529, 31114, 27838,…
$ Seasons_Spring                      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Seasons_Summer                      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Seasons_Winter                      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Holiday_No.Holiday                  &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ DayType_Weekend                     &lt;dbl&gt; 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1…
$ Seasons_Spring_x_Holiday_No.Holiday &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Seasons_Summer_x_Holiday_No.Holiday &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Seasons_Winter_x_Holiday_No.Holiday &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Seasons_Spring_x_MeanTempC          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Seasons_Summer_x_MeanTempC          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Seasons_Winter_x_MeanTempC          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ MeanTempC_x_TotalRainfallMm         &lt;dbl&gt; -0.3100581848, 2.4547443682, -0.26…
$ TotalRainfallMm_poly_2              &lt;dbl&gt; 0.08852698, 7.05865086, 0.08852698…
$ TotalSnowfallCm_poly_2              &lt;dbl&gt; 0.0446049, 0.0446049, 0.0446049, 0…
$ MeanTempC_poly_2                    &lt;dbl&gt; 1.085952e+00, 8.536716e-01, 7.9932…
$ MeanHumidityPercent_poly_2          &lt;dbl&gt; 0.0466964737, 2.6836170430, 0.8595…
$ MeanWindSpeedMs_poly_2              &lt;dbl&gt; 0.1076654458, 1.1876127469, 0.6631…
$ MeanVisibility10M_poly_2            &lt;dbl&gt; 1.317103021, 0.027387894, 0.004437…
$ MeanDewPointC_poly_2                &lt;dbl&gt; 0.722451646, 1.570406851, 1.041197…
$ MeanSolarMjm2_poly_2                &lt;dbl&gt; 0.68468889, 1.89633514, 0.99249392…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(TestingProcessed3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 90
Columns: 29
$ TotalRainfallMm                     &lt;dbl&gt; -0.297534830, -0.288971505, -0.186…
$ TotalSnowfallCm                     &lt;dbl&gt; -0.2111987, -0.2111987, 0.7497533,…
$ MeanTempC                           &lt;dbl&gt; -1.3016303, -1.1180044, -1.0881119…
$ MeanHumidityPercent                 &lt;dbl&gt; -0.79607542, -0.35272399, 0.871372…
$ MeanWindSpeedMs                     &lt;dbl&gt; -0.27064094, 3.02745738, -1.722091…
$ MeanVisibility10M                   &lt;dbl&gt; 0.9003354, -0.1185147, -0.4714765,…
$ MeanDewPointC                       &lt;dbl&gt; -1.3344653, -1.0566147, -0.6930748…
$ MeanSolarMjm2                       &lt;dbl&gt; -1.03821536, -0.93175376, -1.01614…
$ TotalBikeCount                      &lt;dbl&gt; 9539, 8729, 6669, 8032, 4632, 3776…
$ Seasons_Spring                      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Seasons_Summer                      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Seasons_Winter                      &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ Holiday_No.Holiday                  &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ DayType_Weekend                     &lt;dbl&gt; 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0…
$ Seasons_Spring_x_Holiday_No.Holiday &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Seasons_Summer_x_Holiday_No.Holiday &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Seasons_Winter_x_Holiday_No.Holiday &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ Seasons_Spring_x_MeanTempC          &lt;dbl&gt; 0.0000000, 0.0000000, 0.0000000, 0…
$ Seasons_Summer_x_MeanTempC          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Seasons_Winter_x_MeanTempC          &lt;dbl&gt; -1.3016303, -1.1180044, -1.0881119…
$ MeanTempC_x_TotalRainfallMm         &lt;dbl&gt; 0.387280348, 0.323071426, 0.202619…
$ TotalRainfallMm_poly_2              &lt;dbl&gt; 8.852698e-02, 8.350453e-02, 3.4674…
$ TotalSnowfallCm_poly_2              &lt;dbl&gt; 0.04460490, 0.04460490, 0.56213003…
$ MeanTempC_poly_2                    &lt;dbl&gt; 1.69424142, 1.24993393, 1.18398742…
$ MeanHumidityPercent_poly_2          &lt;dbl&gt; 0.633736075, 0.124414210, 0.759289…
$ MeanWindSpeedMs_poly_2              &lt;dbl&gt; 0.073246517, 9.165498196, 2.965599…
$ MeanVisibility10M_poly_2            &lt;dbl&gt; 0.81060391, 0.01404574, 0.22229013…
$ MeanDewPointC_poly_2                &lt;dbl&gt; 1.78079770, 1.11643457, 0.48035261…
$ MeanSolarMjm2_poly_2                &lt;dbl&gt; 1.0778911330, 0.8681650649, 1.0325…</code></pre>
</div>
</div>
</section>
</section>
<section id="model-fit" class="level3">
<h3 class="anchored" data-anchor-id="model-fit">Model Fit</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Ensuring reproducibility</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Defining what model to fit and what engine to use</span></span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>ModelSpec <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">|&gt;</span> <span class="fu">set_engine</span>(<span class="st">"lm"</span>)</span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Recipe 1 workflow and cross-validation</span></span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a>Wf1 <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span> <span class="fu">add_model</span>(ModelSpec) <span class="sc">|&gt;</span> <span class="fu">add_recipe</span>(Recipe1)</span>
<span id="cb84-9"><a href="#cb84-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-10"><a href="#cb84-10" aria-hidden="true" tabindex="-1"></a>Results1 <span class="ot">&lt;-</span> <span class="fu">fit_resamples</span>(</span>
<span id="cb84-11"><a href="#cb84-11" aria-hidden="true" tabindex="-1"></a>  Wf1, </span>
<span id="cb84-12"><a href="#cb84-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">resamples =</span> CvFolds, </span>
<span id="cb84-13"><a href="#cb84-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics =</span> <span class="fu">metric_set</span>(rmse, rsq), </span>
<span id="cb84-14"><a href="#cb84-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">control =</span> <span class="fu">control_resamples</span>(<span class="at">save_pred =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `all_of()` outside of a selecting function was deprecated in tidyselect
1.2.0.
ℹ See details at
  &lt;https://tidyselect.r-lib.org/reference/faq-selection-context.html&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Recipe 2 workflow and cross-validation</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>Wf2 <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span> <span class="fu">add_model</span>(ModelSpec) <span class="sc">|&gt;</span> <span class="fu">add_recipe</span>(Recipe2)</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>Results2 <span class="ot">&lt;-</span> <span class="fu">fit_resamples</span>(</span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>  Wf2, </span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">resamples =</span> CvFolds, </span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics =</span> <span class="fu">metric_set</span>(rmse, rsq), </span>
<span id="cb86-8"><a href="#cb86-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">control =</span> <span class="fu">control_resamples</span>(<span class="at">save_pred =</span> <span class="cn">TRUE</span>)</span>
<span id="cb86-9"><a href="#cb86-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb86-10"><a href="#cb86-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-11"><a href="#cb86-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Recipe 3 workflow and cross-validation</span></span>
<span id="cb86-12"><a href="#cb86-12" aria-hidden="true" tabindex="-1"></a>Wf3 <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span> <span class="fu">add_model</span>(ModelSpec) <span class="sc">|&gt;</span> <span class="fu">add_recipe</span>(Recipe3)</span>
<span id="cb86-13"><a href="#cb86-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-14"><a href="#cb86-14" aria-hidden="true" tabindex="-1"></a>Results3 <span class="ot">&lt;-</span> <span class="fu">fit_resamples</span>(</span>
<span id="cb86-15"><a href="#cb86-15" aria-hidden="true" tabindex="-1"></a>  Wf3, </span>
<span id="cb86-16"><a href="#cb86-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">resamples =</span> CvFolds, </span>
<span id="cb86-17"><a href="#cb86-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics =</span> <span class="fu">metric_set</span>(rmse, rsq), </span>
<span id="cb86-18"><a href="#cb86-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">control =</span> <span class="fu">control_resamples</span>(<span class="at">save_pred =</span> <span class="cn">TRUE</span>)</span>
<span id="cb86-19"><a href="#cb86-19" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb86-20"><a href="#cb86-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-21"><a href="#cb86-21" aria-hidden="true" tabindex="-1"></a><span class="co">#Compare the 3 models</span></span>
<span id="cb86-22"><a href="#cb86-22" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(</span>
<span id="cb86-23"><a href="#cb86-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">Results1 =</span> <span class="fu">collect_metrics</span>(Results1),</span>
<span id="cb86-24"><a href="#cb86-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">Results2 =</span> <span class="fu">collect_metrics</span>(Results2),</span>
<span id="cb86-25"><a href="#cb86-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">Results3 =</span> <span class="fu">collect_metrics</span>(Results3),</span>
<span id="cb86-26"><a href="#cb86-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">.id =</span> <span class="st">"Recipe"</span></span>
<span id="cb86-27"><a href="#cb86-27" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  Recipe   .metric .estimator     mean     n  std_err .config        
  &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;         &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt; &lt;chr&gt;          
1 Results1 rmse    standard   3895.       10 147.     pre0_mod0_post0
2 Results1 rsq     standard      0.850    10   0.0142 pre0_mod0_post0
3 Results2 rmse    standard   2830.       10 189.     pre0_mod0_post0
4 Results2 rsq     standard      0.922    10   0.0132 pre0_mod0_post0
5 Results3 rmse    standard   2768.       10 180.     pre0_mod0_post0
6 Results3 rsq     standard      0.925    10   0.0124 pre0_mod0_post0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Final Fit</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>FinalFit <span class="ot">&lt;-</span> <span class="fu">last_fit</span>(Wf2, DailyDataSplit)</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_metrics</span>(FinalFit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 4
  .metric .estimator .estimate .config        
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;          
1 rmse    standard    3753.    pre0_mod0_post0
2 rsq     standard       0.840 pre0_mod0_post0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Extract coefficients</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>FinalModel <span class="ot">&lt;-</span> <span class="fu">extract_fit_parsnip</span>(FinalFit)</span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(FinalModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 21 × 5
   term                estimate std.error statistic  p.value
   &lt;chr&gt;                  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1 (Intercept)           17715.     1327.   13.3    7.97e-31
 2 TotalRainfallMm       -2617.      313.   -8.37   4.72e-15
 3 TotalSnowfallCm        -281.      174.   -1.62   1.07e- 1
 4 MeanTempC               162.     3105.    0.0522 9.58e- 1
 5 MeanHumidityPercent   -1611.     1181.   -1.36   1.74e- 1
 6 MeanWindSpeedMs        -671.      187.   -3.59   3.98e- 4
 7 MeanVisibility10M       327.      249.    1.31   1.90e- 1
 8 MeanDewPointC          5788.     3566.    1.62   1.06e- 1
 9 MeanSolarMjm2          3172.      329.    9.63   8.54e-19
10 Seasons_Spring        -2765.     2362.   -1.17   2.43e- 1
# ℹ 11 more rows</code></pre>
</div>
</div>
<p><strong>The 10-fold cross-validation shows that Recipe 3 was the best model to choose as the final given it had the lowest RMSE (2768) and highest R-Squared (0.925). The recipe that contains both the interactions as well as the squared terms had the best predictive accuracy of the three recipes. When the interactions were included in the model, there wasa big increase in predictive accuracy (Recipe 1: RMSE = 3895 / RSq = 0.850 vs Recipe 2: RMSE = 0.922 / RSq = 0.922). Although it appears insignificant, the accuracy of the model further improved when the quadratic terms were introduced. [Recipe 3 &gt; Recipe 2 &gt; Recipe 1 (in terms of predictive accuracy)]</strong></p>
</section>
</section>
<section id="homework-9" class="level2">
<h2 class="anchored" data-anchor-id="homework-9">Homework 9</h2>
<section id="lasso-model" class="level3">
<h3 class="anchored" data-anchor-id="lasso-model">Lasso Model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Define Lasso Model</span></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>LassoMod <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>(<span class="at">penalty =</span> <span class="fu">tune</span>(), <span class="at">mixture =</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"glmnet"</span>)</span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-7"><a href="#cb92-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Workflow (Recipe1 and Lasso Model)</span></span>
<span id="cb92-8"><a href="#cb92-8" aria-hidden="true" tabindex="-1"></a>WfLasso <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span> <span class="fu">add_model</span>(LassoMod) <span class="sc">|&gt;</span> <span class="fu">add_recipe</span>(Recipe1)</span>
<span id="cb92-9"><a href="#cb92-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-10"><a href="#cb92-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Tuning grid for Lambda</span></span>
<span id="cb92-11"><a href="#cb92-11" aria-hidden="true" tabindex="-1"></a>LassoGrid <span class="ot">&lt;-</span> <span class="fu">grid_regular</span>(</span>
<span id="cb92-12"><a href="#cb92-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">penalty</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="dv">1</span>)),</span>
<span id="cb92-13"><a href="#cb92-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels =</span> <span class="dv">30</span></span>
<span id="cb92-14"><a href="#cb92-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb92-15"><a href="#cb92-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-16"><a href="#cb92-16" aria-hidden="true" tabindex="-1"></a><span class="co">#Tuning Lasso Model </span></span>
<span id="cb92-17"><a href="#cb92-17" aria-hidden="true" tabindex="-1"></a>LassoTune <span class="ot">&lt;-</span> <span class="fu">tune_grid</span>(</span>
<span id="cb92-18"><a href="#cb92-18" aria-hidden="true" tabindex="-1"></a>  WfLasso,</span>
<span id="cb92-19"><a href="#cb92-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">resamples =</span> CvFolds,</span>
<span id="cb92-20"><a href="#cb92-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">grid =</span> LassoGrid,</span>
<span id="cb92-21"><a href="#cb92-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics =</span> <span class="fu">metric_set</span>(rmse, rsq, mae),</span>
<span id="cb92-22"><a href="#cb92-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">control =</span> <span class="fu">control_grid</span>(<span class="at">save_pred =</span> <span class="cn">TRUE</span>)</span>
<span id="cb92-23"><a href="#cb92-23" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb92-24"><a href="#cb92-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-25"><a href="#cb92-25" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_metrics</span>(LassoTune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 90 × 7
     penalty .metric .estimator     mean     n  std_err .config         
       &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;         &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt; &lt;chr&gt;           
 1 0.00001   mae     standard   3111.       10 122.     pre0_mod01_post0
 2 0.00001   rmse    standard   3868.       10 142.     pre0_mod01_post0
 3 0.00001   rsq     standard      0.852    10   0.0136 pre0_mod01_post0
 4 0.0000161 mae     standard   3111.       10 122.     pre0_mod02_post0
 5 0.0000161 rmse    standard   3868.       10 142.     pre0_mod02_post0
 6 0.0000161 rsq     standard      0.852    10   0.0136 pre0_mod02_post0
 7 0.0000259 mae     standard   3111.       10 122.     pre0_mod03_post0
 8 0.0000259 rmse    standard   3868.       10 142.     pre0_mod03_post0
 9 0.0000259 rsq     standard      0.852    10   0.0136 pre0_mod03_post0
10 0.0000418 mae     standard   3111.       10 122.     pre0_mod04_post0
# ℹ 80 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Select best Lambda based on RMSE</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>BestLasso<span class="ot">&lt;-</span> <span class="fu">select_best</span>(LassoTune, <span class="at">metric =</span> <span class="st">"rmse"</span>)</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>BestLasso</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  penalty .config         
    &lt;dbl&gt; &lt;chr&gt;           
1 0.00001 pre0_mod01_post0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Finalize with best Lambda</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>FinalLassoWf <span class="ot">&lt;-</span> <span class="fu">finalize_workflow</span>(WfLasso, BestLasso)</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Final Fit &amp; Evaluate Performance</span></span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a>FinalLassoFit <span class="ot">&lt;-</span> <span class="fu">last_fit</span>(</span>
<span id="cb96-6"><a href="#cb96-6" aria-hidden="true" tabindex="-1"></a>  FinalLassoWf,</span>
<span id="cb96-7"><a href="#cb96-7" aria-hidden="true" tabindex="-1"></a>  DailyDataSplit,</span>
<span id="cb96-8"><a href="#cb96-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics =</span> <span class="fu">metric_set</span>(rmse, rsq, mae)</span>
<span id="cb96-9"><a href="#cb96-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb96-10"><a href="#cb96-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-11"><a href="#cb96-11" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_metrics</span>(FinalLassoFit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  .metric .estimator .estimate .config        
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;          
1 rmse    standard    4770.    pre0_mod0_post0
2 rsq     standard       0.748 pre0_mod0_post0
3 mae     standard    3687.    pre0_mod0_post0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Extra Final Lasso</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>LassoModel <span class="ot">&lt;-</span> FinalLassoFit <span class="sc">|&gt;</span> <span class="fu">extract_workflow</span>() <span class="sc">|&gt;</span> <span class="fu">extract_fit_parsnip</span>()</span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Collecting Coefficients</span></span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a>LassoCo <span class="ot">&lt;-</span> <span class="fu">tidy</span>(LassoModel, <span class="at">penalty =</span> BestLasso<span class="sc">$</span>penalty)</span>
<span id="cb98-6"><a href="#cb98-6" aria-hidden="true" tabindex="-1"></a>LassoCo</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 14 × 3
   term                estimate penalty
   &lt;chr&gt;                  &lt;dbl&gt;   &lt;dbl&gt;
 1 (Intercept)          20282.  0.00001
 2 TotalRainfallMm      -2249.  0.00001
 3 TotalSnowfallCm       -371.  0.00001
 4 MeanTempC             1020.  0.00001
 5 MeanHumidityPercent      0   0.00001
 6 MeanWindSpeedMs       -887.  0.00001
 7 MeanVisibility10M      -60.1 0.00001
 8 MeanDewPointC         2469.  0.00001
 9 MeanSolarMjm2         4607.  0.00001
10 Seasons_Spring       -4996.  0.00001
11 Seasons_Summer       -3272.  0.00001
12 Seasons_Winter       -8008.  0.00001
13 Holiday_No.Holiday    2507.  0.00001
14 DayType_Weekend      -2099.  0.00001</code></pre>
</div>
</div>
</section>
<section id="regression-tree-model" class="level3">
<h3 class="anchored" data-anchor-id="regression-tree-model">Regression Tree Model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Define Tree Model</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>TreeMod <span class="ot">&lt;-</span> <span class="fu">decision_tree</span>(</span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">cost_complexity =</span> <span class="fu">tune</span>(),</span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">tree_depth =</span> <span class="fu">tune</span>(),</span>
<span id="cb100-5"><a href="#cb100-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">min_n =</span> <span class="fu">tune</span>()</span>
<span id="cb100-6"><a href="#cb100-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span> </span>
<span id="cb100-7"><a href="#cb100-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"rpart"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb100-8"><a href="#cb100-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"regression"</span>)</span>
<span id="cb100-9"><a href="#cb100-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-10"><a href="#cb100-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Workflow (Recipe 1 &amp; Regression Tree)</span></span>
<span id="cb100-11"><a href="#cb100-11" aria-hidden="true" tabindex="-1"></a>WfTree <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">|&gt;</span> <span class="fu">add_model</span>(TreeMod) <span class="sc">|&gt;</span> <span class="fu">add_recipe</span>(Recipe1)</span>
<span id="cb100-12"><a href="#cb100-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-13"><a href="#cb100-13" aria-hidden="true" tabindex="-1"></a><span class="co">#Tuning grid</span></span>
<span id="cb100-14"><a href="#cb100-14" aria-hidden="true" tabindex="-1"></a>TreeGrid <span class="ot">&lt;-</span> <span class="fu">grid_regular</span>(</span>
<span id="cb100-15"><a href="#cb100-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cost_complexity</span>(<span class="fu">c</span>(<span class="sc">-</span><span class="dv">5</span>,<span class="sc">-</span><span class="dv">1</span>)),</span>
<span id="cb100-16"><a href="#cb100-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tree_depth</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">2</span>L, <span class="dv">10</span>L)),</span>
<span id="cb100-17"><a href="#cb100-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">min_n</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">5</span>L, <span class="dv">10</span>L)),</span>
<span id="cb100-18"><a href="#cb100-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">5</span>)</span>
<span id="cb100-19"><a href="#cb100-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb100-20"><a href="#cb100-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-21"><a href="#cb100-21" aria-hidden="true" tabindex="-1"></a><span class="co">#Tuning Model</span></span>
<span id="cb100-22"><a href="#cb100-22" aria-hidden="true" tabindex="-1"></a>TreeTune <span class="ot">&lt;-</span> <span class="fu">tune_grid</span>(</span>
<span id="cb100-23"><a href="#cb100-23" aria-hidden="true" tabindex="-1"></a>  WfTree,</span>
<span id="cb100-24"><a href="#cb100-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">resamples =</span> CvFolds,</span>
<span id="cb100-25"><a href="#cb100-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">grid =</span> TreeGrid,</span>
<span id="cb100-26"><a href="#cb100-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics =</span> <span class="fu">metric_set</span>(rmse, rsq, mae),</span>
<span id="cb100-27"><a href="#cb100-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">control =</span> <span class="fu">control_grid</span>(<span class="at">save_pred =</span> <span class="cn">TRUE</span>)</span>
<span id="cb100-28"><a href="#cb100-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb100-29"><a href="#cb100-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-30"><a href="#cb100-30" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_metrics</span>(TreeTune)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 375 × 9
   cost_complexity tree_depth min_n .metric .estimator     mean     n  std_err
             &lt;dbl&gt;      &lt;int&gt; &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;         &lt;dbl&gt; &lt;int&gt;    &lt;dbl&gt;
 1         0.00001          2     5 mae     standard   3553.       10 220.    
 2         0.00001          2     5 rmse    standard   4633.       10 283.    
 3         0.00001          2     5 rsq     standard      0.794    10   0.0319
 4         0.00001          2     6 mae     standard   3553.       10 220.    
 5         0.00001          2     6 rmse    standard   4633.       10 283.    
 6         0.00001          2     6 rsq     standard      0.794    10   0.0319
 7         0.00001          2     7 mae     standard   3553.       10 220.    
 8         0.00001          2     7 rmse    standard   4633.       10 283.    
 9         0.00001          2     7 rsq     standard      0.794    10   0.0319
10         0.00001          2     8 mae     standard   3553.       10 220.    
# ℹ 365 more rows
# ℹ 1 more variable: .config &lt;chr&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Selecting the Best Model</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>BestTree <span class="ot">&lt;-</span> <span class="fu">select_best</span>(TreeTune, <span class="at">metric =</span> <span class="st">"rmse"</span>)</span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a>BestTree</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  cost_complexity tree_depth min_n .config          
            &lt;dbl&gt;      &lt;int&gt; &lt;int&gt; &lt;chr&gt;            
1         0.00001         10     8 pre0_mod024_post0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Finalize Workflow</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>FinalTreeWf <span class="ot">&lt;-</span> <span class="fu">finalize_workflow</span>(WfTree, BestTree)</span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Final Fit &amp; Evaluate Performance</span></span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a>FinalTreeFit <span class="ot">&lt;-</span> <span class="fu">last_fit</span>(</span>
<span id="cb104-6"><a href="#cb104-6" aria-hidden="true" tabindex="-1"></a>  FinalTreeWf,</span>
<span id="cb104-7"><a href="#cb104-7" aria-hidden="true" tabindex="-1"></a>  DailyDataSplit,</span>
<span id="cb104-8"><a href="#cb104-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics =</span> <span class="fu">metric_set</span>(rmse, rsq, mae)</span>
<span id="cb104-9"><a href="#cb104-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb104-10"><a href="#cb104-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-11"><a href="#cb104-11" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_metrics</span>(FinalTreeFit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  .metric .estimator .estimate .config        
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;          
1 rmse    standard    3996.    pre0_mod0_post0
2 rsq     standard       0.833 pre0_mod0_post0
3 mae     standard    2910.    pre0_mod0_post0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Extract Final Tree</span></span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a>FinalTreeModel <span class="ot">&lt;-</span> FinalTreeFit <span class="sc">|&gt;</span> <span class="fu">extract_workflow</span>() <span class="sc">|&gt;</span> <span class="fu">extract_fit_parsnip</span>()</span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-4"><a href="#cb106-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Plot Tree</span></span>
<span id="cb106-5"><a href="#cb106-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(</span>
<span id="cb106-6"><a href="#cb106-6" aria-hidden="true" tabindex="-1"></a>  FinalTreeModel<span class="sc">$</span>fit, </span>
<span id="cb106-7"><a href="#cb106-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Final Regression Tree Model"</span>, </span>
<span id="cb106-8"><a href="#cb106-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">roundint =</span> <span class="cn">FALSE</span>,</span>
<span id="cb106-9"><a href="#cb106-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="dv">2</span>,</span>
<span id="cb106-10"><a href="#cb106-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">cex =</span> <span class="fl">0.15</span>,</span>
<span id="cb106-11"><a href="#cb106-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">fallen.leaves =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: labs do not fit even at cex 0.15, there may be some overplotting</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="BikeRentalData_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>